### ISSUE TITLE
Feature Request: Additional Host Metadata via config

### ISSUE THREAD

**Issue by cdhunt** [signalfx/signalfx-agent#1029]
I'd like to be able to list of properties in the hostmetadata config (which there is currently no config options) to pass through as host metadata. This would allow me to create this file from our configuration management system and provide additional host properties that we have in that system.

Example config yaml:

```yml
monitors:
  - type: host-metadata
    customproperties:
      property1: value1
      property2: value2
```

These could just be read from the config and passed through as another [metadataFuncs](https://github.com/signalfx/signalfx-agent/blob/master/internal/monitors/metadata/hostmetadata/hostmetadata.go#L53)
