### ISSUE TITLE
Discovery Rule on container_labels not configuring any monitors

### ISSUE THREAD

**Issue by daviddyball** [signalfx/signalfx-agent#1089]
I'm having a few issues getting a global discovery rule working. Most of our microservices behave the same, so I want to write a rule that will work for 90% of them, but somethings not working correctly and I can't quite pinpoint why.

I have this in my `agent.yaml`:
```
monitors:
  - type: prometheus-exporter
    discoveryRule: Get(container_labels, "metrics") == "true" && private_port == "9125"
    extraDimensionsFromEndpoint:
      app: Get(container_labels, "app")
```

and I have a `Pod` spec of:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-service
  namespace: default
  labels:
    name: "my-service"
    metrics: "true"
spec:
  containers:
  - name: my-service
    image: my-service:latest
```

This isn't configuring any monitors for me :confused: If I change the `discoveryRule` to `container_image =~ "my-service"` it works fine.

He're's the output of `signalfx-agent status endpoints` if that helps:
```
 - internalId: my-service-5ccd5bb89c-g577w-4995517-9125 (UNMONITORED)
   alternate_port: 0
   container_command: 
   container_id: f9387b00f26064c02c6cb5ffb13c5c1f10a429e857f5a2eb854e785c0cdb1c57
   container_image: my-service:latest
   container_labels: map[app:my-service metrics:true pod-template-hash:5ccd5bb89c release:my-service-1]
   container_name: my-service
   container_names: [my-service]
   container_spec_name: my-service
   container_state: running
   discovered_by: k8s-api
   has_port: true
   host: 100.96.5.36
   id: my-service-5ccd5bb89c-g577w-4995517-9125
   ip_address: 100.96.5.36
   kubernetes_annotations: map[artifact.spinnaker.io/location:default cni.projectcalico.org/podIP:100.96.5.36/32]
   kubernetes_namespace: default
   kubernetes_pod_name: my-service-5ccd5bb89c-g577w
   kubernetes_pod_uid: 4995517c-0d1b-11ea-9d1e-06033b20cc02
   name: metrics
   network_port: 9125
   orchestrator: 1
   pod_metadata: &ObjectMeta{Name:my-service-5ccd5bb89c-g577w,GenerateName:my-service-5ccd5bb89c-,Namespace:default,SelfLink:/api/v1/namespaces/default/pods/my-service-5ccd5bb89c-g577w,UID:4995517c-0d1b-11ea-9d1e-06033b20cc02,ResourceVersion:34107591,Generation:0,CreationTimestamp:2019-11-22 11:29:03 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{app: my-service,metrics: true,pod-template-hash: 5ccd5bb89c,release: my-service-1,},Annotations:map[string]string{cni.projectcalico.org/podIP: 100.96.5.36/32,},OwnerReferences:[{apps/v1 ReplicaSet my-service-5ccd5bb89c 498e8e1f-0d1b-11ea-9d1e-06033b20cc02 0xc00235838a 0xc00235838b}],Finalizers:[],ClusterName:,Initializers:nil,}
   pod_spec: &PodSpec{Volumes:[{logging-config {nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil ConfigMapVolumeSource{LocalObjectReference:LocalObjectReference{Name:my-service-logging-v000,},Items:[{content config.xml <nil>}],DefaultMode:*420,Optional:nil,} nil nil nil nil nil nil nil nil}} {default-token-qktlw {nil nil nil nil nil &SecretVolumeSource{SecretName:default-token-qktlw,Items:[],DefaultMode:*420,Optional:nil,} nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil}}],Containers:[{my-service my-service:latest [/bin/bash /start.sh] []  [{http 0 80 TCP } {metrics 0 9125 TCP }] [{ ConfigMapEnvSource{LocalObjectReference:LocalObjectReference{Name:my-service-environment-v000,},Optional:nil,} nil} { nil &SecretEnvSource{LocalObjectReference:LocalObjectReference{Name:my-service-secrets,},Optional:nil,}}] [] {map[memory:{{566231040 0} {<nil>} 540Mi BinarySI}] map[cpu:{{600 -3} {<nil>} 600m DecimalSI} memory:{{566231040 0} {<nil>} 540Mi BinarySI}]} [{logging-config false /config/logging  <nil>} {default-token-qktlw true /var/run/secrets/kubernetes.io/serviceaccount  <nil>}] [] &Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/ping,Port:http,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:60,TimeoutSeconds:5,PeriodSeconds:30,SuccessThreshold:1,FailureThreshold:3,} &Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/ping,Port:http,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:60,TimeoutSeconds:5,PeriodSeconds:30,SuccessThreshold:1,FailureThreshold:3,} nil /dev/termination-log File IfNotPresent nil false false false}],RestartPolicy:Always,TerminationGracePeriodSeconds:*30,ActiveDeadlineSeconds:nil,DNSPolicy:ClusterFirst,NodeSelector:map[string]string{kops.k8s.io/instancegroup: au-production,},ServiceAccountName:default,DeprecatedServiceAccount:default,NodeName:ip-10-31-51-23.ap-southeast-2.compute.internal,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:&PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,RunAsGroup:nil,Sysctls:[],},ImagePullSecrets:[],Hostname:,Subdomain:,Affinity:nil,SchedulerName:default-scheduler,InitContainers:[],AutomountServiceAccountToken:nil,Tolerations:[{node.kubernetes.io/not-ready Exists  NoExecute 0xc002358670} {node.kubernetes.io/unreachable Exists  NoExecute 0xc0023586a0}],HostAliases:[],PriorityClassName:,Priority:*0,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[],RuntimeClassName:nil,EnableServiceLinks:*true,}
   port: 9125
   port_labels: map[]
   port_type: TCP
   private_port: 9125
   public_port: 0
   target: hostport
```

Any ideas what's going on?
