### ISSUE TITLE
MySQL : reportHost not working

### ISSUE THREAD

**Issue by Poil** [signalfx/signalfx-agent#1297]
Hi,

I try to report the real MySQL host, so I try to set reportHost to true but the host label remains to my signalfx-agent host. (https://docs.signalfx.com/en/latest/integrations/agent/monitors/collectd-mysql.html)

My configuration

```yaml
# (...)
monitors:
# (...)
-   '#from': /etc/signalfx/conf.d/*.yml
```

```yaml
- type: collectd/mysql
  host: "app-xxx-euw-preprod-mysql.mysql.database.azure.com"
  port: 3306
  reportHost: yes # also tried no/true/false
  username: "claranet@app-xxxx-euw-preprod-mysql"
  password: "xxxxxxxx"
  databases: [{"name": "xxx_preprod"}]
```

Also, it should be nice to be able to link (add label) to a cloud resource id, not sure if it's possible or not today, I tried this but not working :

```yaml
---
- type: collectd/mysql
# (...)
  extraSpanTags:
     azure_resource_name: app-xxxx-euw-dev-mysql
...
```

And the reported plugin_instance is `_my_database` (the first underscore should not be here)

Best regards,
