### ISSUE TITLE
Show observer dimensions discovered from labels in status command

### ISSUE THREAD

**Issue by hreeder** [signalfx/signalfx-agent#1337]
Given the following:

Agent Config:
```yaml
observers:
- type: docker
  labelsToDimensions:
    com.foo.bar: MyDimension
```

Docker Compose:
```yaml
version: '3'
services:
  redis:
    image: redis
    labels:
      agent.signalfx.com.monitorType.6379: collectd/redis
      com.foo.bar: SuperAwesomeRedisInstance
```

I would like to be able to run `signalfx-agent status monitors` and see the dimension `MyDimension: SuperAwesomeRedisInstance` somewhere to be able to validate that the labelsToDimensions configuration has parsed my container labels correctly (especially if we use long label names).

Is this a feasible thing to add?

**Comment by keitwb** [comment]
I would recommend using the `tap-dps` subcommand and filtering by either one of the docker metric names or the expected dimension name.  So something like either:

`signalfx-agent tap-dps -metric 'cpu.usage.total'` (get a single docker metric)

OR

`signalfx-agent tap-dps -dims '{plugin: docker}'` (get all docker monitor datapoints)

This will then show each datapoint as it comes through as well as a table showing the final dimensions on that datapoint as they will be sent to our backend.

Try that out and let us know if it helps.

**Comment by hreeder** [comment]
That does help as an alternative, however my thought would have been to include the discovered dimensions somewhere like so, as this is my first stop for checking a monitor has been configured properly.

```
11. collectd/redis
    Reporting Interval (seconds): 10
    Enabled Metrics: [
      counter.total_net_input_bytes, counter.expired_keys, counter.total_net_output_bytes, derive.keyspace_misses,
      bytes.used_memory_rss, counter.commands_processed, counter.evicted_keys, gauge.blocked_clients, bytes.used_memory,
      derive.keyspace_hits, gauge.connected_clients, gauge.master_repl_offset, gauge.slave_repl_offset,
      counter.rejected_connections, counter.used_cpu_sys, counter.used_cpu_user
    ]
    Discovery Rule:
    Monitored Endpoint ID: redis_redis_1-17d4ca3ef0ef-6379
    Config:
      type: collectd/redis
      discoveryRule: ""
      validateDiscoveryRule:
      extraDimensions:
      extraSpanTags:
      extraSpanTagsFromEndpoint:
      defaultSpanTags:
      defaultSpanTagsFromEndpoint:
      extraDimensionsFromEndpoint:
      configEndpointMappings:
      intervalSeconds: 10
      solo: false
      datapointsToExclude:
      disableHostDimensions: false
      disableEndpointDimensions: false
      dimensionTransformations:
      extraMetrics:
      extraGroups:
      pythonBinary: ""
      host: 172.18.0.2
      port: 6379
      name: redis_redis_1-17d4ca3ef0ef-6379
      auth:
      sendListLengths:
      verbose: false
```
