### ISSUE TITLE
Missing Dimensions from Pod Labels When Using kubelet-metrics

### ISSUE THREAD

**Issue by daviddyball** [signalfx/signalfx-agent#1427]
Hi,

We recently upgraded to `v5.4.2` from `4.x` after upgrading our K8s clusters to `1.18`. We alsomade the switch from `kubelet-stats` over to `kubelet-metrics` as instructed, however the metrics shipped from the `kubelet-stats` monitor no longer contain our Kubernetes pod labels as dimensions. Specifically we used to ship an `app` label that our teams use when generating their graphs.

Our monitor configuration is:

```
monitors:
- type: kubelet-metrics
  usePodsEndpoint: true
  kubeletAPI:
    url: http://${MY_NODE_IP}:10255
    authType: serviceAccount
    skipVerify: true
  extraDimensions:
    metric_source: kubelet-stats
```

Any help you can give is appreciated.

DD
