### ISSUE TITLE
Smart Agent deploy guidance in Kubernetes environments without Docker

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/signalfx-agent#1437]
Hi Team!

I use some k8s Clusters that don't use docker daemon internally ( containerd/cri-o - MicroK8s, OpenShift 4.x, etc). 

The Smart Agent deployment works, despite the docker errors which I assume I can remedy by turning off this docker monitor? 

```
 - type: docker-container-stats
      dockerURL: unix:///var/run/docker.sock
      excludedImages:
       - '*pause-amd64*'
       - 'k8s.gcr.io/pause*'
      labelsToDimensions:
        io.kubernetes.container.name: container_spec_name
        io.kubernetes.pod.name: kubernetes_pod_name
        io.kubernetes.pod.uid: kubernetes_pod_uid
        io.kubernetes.pod.namespace: kubernetes_namespace
```

```
time="2020-08-26T21:06:15Z" level=info msg="Watching for Docker events since 2020-08-26T21:06:15.396519959Z" monitorType=docker-container-stats
time="2020-08-26T21:06:15Z" level=error msg="Error watching docker container events" error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" monitorType=docker-container-stats
```

Beyond that, is there anything else one should consider when deploying to environments like this to ensure I get the most out of sfx dashboards when containerd/cri-o are in play?

In my particular enviro, the containerd.sock is available, though I am not sure there is any monitors that use it?

`/var/snap/microk8s/common/run# ls -la containerd.sock 
srw-rw---- 1 root root 0 Aug 25 10:24 containerd.sock`

More on MicroK8s services/metric ports, in case I can use them in my Smart Agent config?

https://microk8s.io/docs/configuring-services
https://microk8s.io/docs/ports

Helm command used:

```
helm install sfx-smart-agent --namespace sfx --set signalFxAccessToken=blahblahblah --set clusterName=foo --set signalFxRealm=us0 --set fullnameOverride=signalfx-agent signalfx/signalfx-agent
```

configmap:

```
Name:         signalfx-agent-v5
Namespace:    sfx
Labels:       app=signalfx-agent
              app.kubernetes.io/managed-by=Helm
              chart=signalfx-agent-1.5.0
              heritage=Helm
              release=sfx-smart-agent
Annotations:  meta.helm.sh/release-name: sfx-smart-agent
              meta.helm.sh/release-namespace: sfx

Data
====
agent.yaml:
----
signalFxAccessToken: ${SFX_ACCESS_TOKEN}

signalFxRealm: us0

disableHostDimensions: false

etcPath: /hostfs/etc
procPath: /hostfs/proc

enableBuiltInFiltering: true

intervalSeconds: 10

cluster: mattymo-microk8s

writer:
  signalFxEnabled: true

logging:
  level: info
  format: text

globalDimensions:
  kubernetes_cluster: mattymo-microk8s

observers:
- type: k8s-api
  discoverAllPods: false
  discoverNodes: false

monitors:
- type: cpu
- type: filesystems
  hostFSPath: /hostfs
- type: disk-io
- type: net-io
- type: load
- type: memory
- type: host-metadata
- type: processlist
- type: vmem


- type: kubelet-metrics
  kubeletAPI:
    authType: serviceAccount
  usePodsEndpoint: true
  
  

# Collects k8s cluster-level metrics
- type: kubernetes-cluster


- type: docker-container-stats
  dockerURL: unix:///var/run/docker.sock
  excludedImages:
   - '*pause-amd64*'
   - 'k8s.gcr.io/pause*'
  labelsToDimensions:
    io.kubernetes.container.name: container_spec_name
    io.kubernetes.pod.name: kubernetes_pod_name
    io.kubernetes.pod.uid: kubernetes_pod_uid
    io.kubernetes.pod.namespace: kubernetes_namespace


collectd:
  
  readThreads: 5
  writeQueueLimitHigh: 500000
  writeQueueLimitLow: 400000
  timeout: 40
  logLevel: info

metricsToExclude:
  # The StackDriver metadata-agent pod on GKE restarts every few minutes so
  # ignore its containers
  - dimensions:
      container_spec_name: metadata-agent

Events:  <none>
```
