### ISSUE TITLE
Agent parameter disableHostDimensions does not apply to all monitors

### ISSUE THREAD

**Issue by jphilaine** [signalfx/signalfx-agent#1447]
In serverless use case, if we set agent parameter `disableHostDimensions` at `true` and we don't set this parameter at monitor level :
- The agent config is correctly set with value `true`
- But all monitors have an inherited value at `false`

For the moment, I fixes it by adding `disableHostDimensions` at `true` for each monitors, but I think it's not the correct behaviour.

For more informations, I use helm chart in serverless mode. It's easy to reproduce.

Regards,
Jean-Philippe Lainé

**Comment by keitwb** [comment]
@jphilaine can you be more specific on what dimensions you are seeing that you don't expect to see?  Based on the tests I just did,  the top-level `disableHostDimensions` seems to be working fine for what it is intended to do (suppress the `host`, `AWSUniqueId`, `kubernetes_node_uid`, etc. dimensions).

**Comment by jphilaine** [comment]
To give you more informations, see my agent configuration :
````
signalFxAccessToken: ${SFX_ACCESS_TOKEN}

signalFxRealm: eu0

disableHostDimensions: true

[...]

monitors:
  - type: collectd/mysql
    host: &mysqlHost 10.248.128.3
    port: &mysqlPort 3306
    username: &mysqlUser user***
    password: &mysqlPass password***
    databases:
      - name: &mysqlDBName mysql
    extraDimensions: &mysqlDimensions
      check_type: test
````

See `signalfx-agent status config` command result :
```
Agent Configuration:
  signalFxAccessToken: ***************
  ingestUrl: https://ingest.eu0.signalfx.com
  eventEndpointUrl: ""
  traceEndpointUrl: ""
  apiUrl: https://api.eu0.signalfx.com
  signalFxRealm: eu0
  hostname: ""
  useFullyQualifiedHost:
  disableHostDimensions: true
  intervalSeconds: 10
  cloudMetadataTimeout: 2000000000
  globalDimensions:
    env: preprod
    kubernetes_cluster: mycluster
    sfx_monitored: "true"
  globalSpanTags:
  cluster: mycluster
  syncClusterOnHostDimension: false
  validateDiscoveryRules: false
  observers:
  monitors:
  - type: collectd/mysql
    discoveryRule: ""
    validateDiscoveryRule: false
    extraDimensions:
      check_type: test
    extraSpanTags:
    extraSpanTagsFromEndpoint:
    defaultSpanTags:
    defaultSpanTagsFromEndpoint:
    extraDimensionsFromEndpoint:
    configEndpointMappings:
    intervalSeconds: 10
    solo: false
    datapointsToExclude:
    disableHostDimensions: false
    disableEndpointDimensions: false
    metricNameTransformations:
    dimensionTransformations:
    extraMetrics:
    extraGroups:
[...]
```

First, despite having  global parameter `disableHostDimensions: true` in each monitors, the default value is `false`. Is it normal ?
I see this issue for `collectd/mysql` and `elasticsearch`, but it could be present for other untested monitors.
