### ISSUE TITLE
Memory leak or cache issue

### ISSUE THREAD

**Issue by atishpatel** [signalfx/signalfx-agent#1482]
There seems to be some issue with singlafx-agent's memory or cache usage. 

This thread might help with understanding why `kubectl top` and `container_memory_usage_bytes` are different.
https://github.com/kubernetes/dashboard/issues/2105

<img width="1783" alt="Screen Shot 2020-10-06 at 10 45 05 AM" src="https://user-images.githubusercontent.com/6618430/95225270-38ebeb80-07c1-11eb-8745-4b4aeb092ff8.png">
<img width="782" alt="Screen Shot 2020-10-06 at 10 45 52 AM" src="https://user-images.githubusercontent.com/6618430/95225276-3ab5af00-07c1-11eb-987b-098327adf86d.png">

**Comment by keitwb** [comment]
@atishpatel can you send a copy of your config?  Most of the memory usage comes from monitors so it would be helpful to know which might be leaking.

**Comment by atishpatel** [comment]
Here is the configmap. It basically straight from the kube template 
```yaml
---
# Source: signalfx-agent/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: signalfx-agent
  name: signalfx-agent-v5
  namespace: signalfx-agent
data:
  agent.yaml: |
    hostname: ${MY_NODE_NAME}
    signalFxAccessToken: ${SFX_ACCESS_TOKEN}

    signalFxRealm: us0

    etcPath: /hostfs/etc
    procPath: /hostfs/proc

    enableBuiltInFiltering: true

    intervalSeconds: 10

    cluster: %%SFX_CLUSTER_NAME%%

    logging:
      level: info
      format: text

    globalDimensions:
      kubernetes_cluster: %%SFX_CLUSTER_NAME%%

    observers:
    - type: k8s-api

    monitors:
    - type: cpu
    - type: filesystems
      hostFSPath: /hostfs
      mountPoints:
      - "*"
      - "!/var/lib/docker/containers/*"
      - "!/var/lib/docker/overlay2/*"
      - "!/var/lib/kubelet/pods/*"
    - type: disk-io
    - type: net-io
    - type: load
    - type: memory
    - type: host-metadata
    - type: processlist
    - type: vmem
    - type: kubelet-metrics
      kubeletAPI:
        url: https://${MY_NODE_NAME}:10250
        authType: serviceAccount
      usePodsEndpoint: true
    # Collects k8s cluster-level metrics
    - type: kubernetes-cluster
      extraMetrics:
      - kubernetes.container_cpu_request
      - kubernetes.container_memory_request
    - type: docker-container-stats
      dockerURL: unix:///var/run/docker.sock
      excludedImages:
       - '*pause-amd64*'
       - 'k8s.gcr.io/pause*'
      labelsToDimensions:
        io.kubernetes.container.name: container_spec_name
        io.kubernetes.pod.name: kubernetes_pod_name
        io.kubernetes.pod.uid: kubernetes_pod_uid
        io.kubernetes.pod.namespace: kubernetes_namespace


    collectd:
      readThreads: 5
      writeQueueLimitHigh: 500000
      writeQueueLimitLow: 400000
      timeout: 40
      logLevel: info

    metricsToExclude:
      # The StackDriver metadata-agent pod on GKE restarts every few minutes so
      # ignore its containers
      - dimensions:
          container_spec_name: metadata-agent

```
