### ISSUE TITLE
monitors/http Regex dosnt work

### ISSUE THREAD

**Issue by EvilAcid** [signalfx/signalfx-agent#1521]
Hello all

i try to implement the http monitor and check the response with a regex.

but i recive everytime a regex_match = 0 on SignalFx.

Here my Setings:
_Originalurl removed_
```
  - type: http
    intervalSeconds: 120
    disableHostDimensions: true
    extraDimensions:
      application: example
    host: 'www.example.ch'
    path: '/'
    regex: '([oO]bject|[mM]oved)'
    port: 443
    useHTTPS: true
```

Response from the Site with a cUrl
```
<head><title>Object moved</title></head>
<body><h1>Object Moved</h1>This object may be found <a HREF="/example/index.asp">here</a>.</body>
```

So for this, how i should past a Regex string?
i have this regexstring testet on https://regex101.com/

Kind Regards

**Comment by keitwb** [comment]
Is that response a 3xx redirect?  If so, you should set `noRedirects: true` in the monitor config.  Otherwise it seems ok, maybe try removing the parenthesis around the regex (they are unnecessary).

**Comment by EvilAcid** [comment]
Yes, you are right

```
  - type: http
    intervalSeconds: 120
    disableHostDimensions: true
    extraDimensions:
      application: example
    host: 'www.example.ch'
    path: '/'
    regex: '[oO]bject|[mM]oved'
    port: 443
    useHTTPS: true
    noRedirects: true
```

so it is working.

Thanks
