### ISSUE TITLE
[QUESTION] Make a monitor instance unique

### ISSUE THREAD

**Issue by xp-1000** [signalfx/signalfx-agent#1527]
Hello,

I have a little question especially for http monitor but could be useful for others.

Sometimes we can have multiple instances of the same monitor with similar configuration which could lead to reporting "different" datapoint to the same MTS.

Of course the obvious solution is to push as dimension every single parameter to monitor provide.
Nevertheless it is not always relevant and may be even to easy.

For http for example it will ask to add complex dimension definition from "rich" parameter like httpHeaders or for often changing config like the regex.

One solution could be to create some kind of "hash" from the entire montior configuration and push this hash as dimension. This will allow to be sure every single monitor instance produces each one its own MTS.

But I would like to know if you already addressed this kind of need somewhere 

For now, as workaround I set an extrapolation policy to http metrics for all of my related detectors. In case of 2 monitors in "conflict" they will produce each one a datapoint on the same rollup timeframe an extrapolation policy `max` for http latency for example will allow to consider and evaluate the "worst" monitor but it is not ideal.

**Comment by keitwb** [comment]
The best way right now to handle this is to use the `extraDimensions: {}` config on the individual monitors.  Because it is so dependent on your exact usage/configuration as to what it should be, it would be very hard to make some generic behavior.  Also a hash of the config would be undesirable in general normally because a lot of times you don't want different MTSs for different config (it would also make backwards-compatibility difficult).

For example, if you had two `http` monitors that checked the same URL but different regexs you could do something like:

```yaml
monitors:
 - type: http
    host: example.com
    regex: 'Status: No problems'
    extraDimensions:
      check: operational
 - type: http
    host: example.com
    regex: 'Status: outage'
    extraDimensions:
      check: outage
```

This is kind of a contrived example but hopefully it is helpful.
