### ISSUE TITLE
postgresql monitor using 100% CPU

### ISSUE THREAD

**Issue by swbsf** [signalfx/signalfx-agent#1538]
Hello,

I don't know what's causing this in my environment, but basically postgresql monitor is very agressive toward the database and sends zillion of new metrics to SFX so I get throttled on metrics ingestion. Database CPU usage in percent -> 
![image](https://user-images.githubusercontent.com/22593912/100345399-90008680-2fe2-11eb-96fc-5c903ed11f07.png)

Data Table in SFX for a given metric (something obviously wrong with the schemaname, the only one we have on the database is `public`) ->
![image](https://user-images.githubusercontent.com/22593912/100346123-a0653100-2fe3-11eb-9810-51d5417cccbe.png)
Relations ->
![image](https://user-images.githubusercontent.com/22593912/100346507-42851900-2fe4-11eb-808e-6191021d5767.png)

Container running signalfx-agent is using 100% CPU as well.

Env :
* AWS/RDS/Postgres 9.6.15
* signalfx-agent: 5.6.0

Config file:
```
# This agent config file is designed for use within an ECS task.  The agent
# should be as a Fargate service within an ECS task.
signalFxAccessToken: {"#from": "env:ACCESS_TOKEN"}
ingestUrl: {"#from": "env:INGEST_URL", optional: true}
apiUrl: {"#from": "env:API_URL", optional: true}
traceEndpointUrl: {"#from": "env:TRACE_ENDPOINT_URL", optional: true}

intervalSeconds: {"#from": "env:INTERVAL_SECONDS", default: 10}

logging:
  level: {"#from": "env:LOG_LEVEL", default: "info"}

globalDimensions:
  env: {"#from": "env:ENV"}
  region: {"#from": "env:AWS_REGION"}
  sfx_monitored: true

# observers are what discover running services in the environment
observers:
    # Enable the ecs observer to discover other ECS containers running on the
    # same ECS task.
  - type: ecs
    labelsToDimensions: &labelMap
      com.amazonaws.ecs.container-name: signalfx_container

monitors:
  - type: postgresql
    connectionString: "user={{.username}} password={{.password}} sslmode=disable"
    host: {"#from": "env:db_host"}
    params: &psqlParams
      username: {"#from": "env:db_user"}
      password: {"#from": "env:db_pass"}
    databases:
      - '*'
      - '!rdsadmin'
    #masterDBName: &psqlDBName rdsadmin
    extraMetrics:
      - "postgres_xact_rollbacks"
      - "postgres_xact_commits"
      - "postgres_conflicts"
      - "postgres_locks"
      - "postgres_pct_connections"
  - type: collectd/redis
    host: {"#from": "env:redis_host"}
    port: 6379
    extraMetrics:
      - bytes.maxmemory
      - gauge.db0_keys

metricsToExclude:
  - {"#from": "env:METRICS_TO_EXCLUDE", default: [], flatten: true}

# This allows any config above to be completely overridden.  CONFIG_OVERRIDE
# must be given as a YAML/JSON object.
_: {"#from": "env:CONFIG_OVERRIDE", optional: true, flatten: true}

# Required: What format to send data in
writer:
  traceExportFormat: sapm
```

Hope this helps. Just ask if you'd like more info for some debugging.

Steven
