### ISSUE TITLE
Errors connecting to the AKS Nodes Summary Stats

### ISSUE THREAD

**Issue by dubb-b** [signalfx/signalfx-agent#1565]
This seems to only happen on AKS clusters deploying using the helm chart.

level=error msg="Could not get summary metrics" error="failed to get summary stats from Kubelet URL \"http:

I found that if I move the url to the same level as kubeletAPI it works.

I have locally modified the chart to do that, (not in the best manner) but wanted to see if there is something that needs updated?

This is my config now.

```
- type: kubelet-metrics
  kubeletAPI:
    authType: serviceAccount
  usePodsEndpoint: true
  url: http://localhost:10255
```

vs.

```
- type: kubelet-metrics
  kubeletAPI:
    authType: serviceAccount
    url: http://localhost:10255
  usePodsEndpoint: true
```

Maybe I am missing something?

Thanks!
