### ISSUE TITLE
SignalFX agent not ingesting all kubernetes-cluster metric

### ISSUE THREAD

**Issue by VarsChdhry** [signalfx/signalfx-agent#1576]
We deployed SFX agent on windows nodes in AKS, and added kubernetes-cluster monitor in  agent configmap.

As per this doc :[kubernetes-cluster]( https://docs.signalfx.com/en/latest/integrations/agent/monitors/kubernetes-cluster.html#configuration)
SFX should have containers CPU and Memory, request/limits metrics

All Pods running have CPU/Memory limits and request in their deployment yamls. 

We have Limits metrics coming in for both CPU and Memory in Splunk and SignalFX, but we don't have request metrics coming in.

This is config:
```
- type: kubernetes-cluster
      kubernetesAPI:
        authType: serviceAccount
```
Am I missing something?

Thank you!

**Comment by mstumpfx** [comment]
Hi @VarsChdhry 
If you are talking about the `kubernetes.container_memory_request` and `kubernetes.container_cpu_request` metrics, these are not enabled by default. You will need to explicitly add them to your monitor configuration:
```
- type: kubernetes-cluster
      kubernetesAPI:
        authType: serviceAccount
  extraMetrics:
    - kubernetes.container_memory_request
    - kubernetes.container_cpu_request
```
