### ISSUE TITLE
Disable node, pod metadata dimension in SignalFx daemonset

### ISSUE THREAD

**Issue by VarsChdhry** [signalfx/signalfx-agent#1646]
We have deployed SignalFx windows daemonset to send metrics to Splunk. As signalFx cannot send node, pod metadata as dimensions in Splunk, is there any way I can set in daemonset/configmap, so that signalfx daemonset stop trying to update Dimensions. We are having lots of logs from pod about updating dimensions, which makes it noisy. Below are few logs:

 

 
```
level=error msg="Unable to update dimension, retrying" dim="{name: \"kubernetes_uid\"; value: \"4e0c3165-bc4\"; props: map[apppog:0001aappod branch:test-branch AppCode:005 AppTier:public Branch:new-dev-test Deployment:0001-new-dev-test Location:USEast ServiceTier:dev replicaset_creation_timestamp:2021-03-19T20:57:36Z run:orderstatusapi]; tags: map[DataClassification:true]; mergeIntoExisting: false}" error="error making HTTP request to https://api.us0.signalfx.com/v2/dimension/kubernetes_uid/

level=error msg="Unable to update dimension, retrying" dim="{name: \"kubernetes_pod_uid\"; value: \"7ed596ad-11b\"; appcode:002 apptier:public Deployment:002-dev Location:USEast ServiceTier:dev env:dev ]; tags: map[branch:true DataClassification:true]; mergeIntoExisting: true}" error="error making HTTP request to https://api.us0.signalfx.com/v2/dimension/kubernetes_pod_uid/"
```

 Is there way we can stop sending these pod and node dimensions?

 

 There is configmap :

 ```
apiVersion: v1

kind: ConfigMap

metadata:

  name: signalfxagent

  namespace: signalfxagent

data:

  agent.yaml: |

    hostname: {"#from": "env:Node_name"}

    etcPath: /hostfs/etc

    procPath: /hostfs/proc

    enableBuiltInFiltering: true

    intervalSeconds: 10

    cluster: cluster-name

    writer:

      splunk:

        enabled: true

        url:URL

        token: Token

        index:cindex

        skipTLSVerify: true

    logging:

      level: info

      format: text

   

    globalDimensions:

      kubernetes_cluster: cluster-name

    observers:

    - type: k8s-api

      discoverAllPods: true

      discoverNodes: true

    monitors:

    - type: cpu

      extraMetrics:

      - cpu.utilization_per_core

      reportPerCPU: true

   

    - type: filesystems

      hostFSPath: /hostfs

    - type: disk-io

    - type: net-io

    - type: memory

    - type: host-metadata

    - type: processlist

    - type: vmem

    - type: kubelet-metrics

      kubeletAPI:

        url: https://${MY_NODE_IP}:10250

        authType: serviceAccount

      usePodsEndpoint: true

     extraMetrics:

        - container_memory_working_set_bytes

        - container_memory_available_bytes

        - container_memory_major_page_faults

        - container_memory_page_faults

        - container_memory_rss_bytes

      extraGroups:

        - podEphemeralStats

      metricNameTransformations:

        container_memory_working_set_bytes: container_memory_usage_bytes

        container_memory_available_bytes: container_memory_available
```
