### ISSUE TITLE
ERROR -- dropped dimension update, propertiesMaxBuffered exceeded

### ISSUE THREAD

**Issue by AchimGrolimund** [signalfx/signalfx-agent#1780]
Good evening everyone

We have had a lot of error messages in our agent since last night. The configuration has not been adjusted since> 1M (Configmap / Deamonset) below I have given an excerpt from the logs.

I see that the RAM consumption, which is normal at around 100-300Mb, increases to over 10Gb. -> see picture.

I have also included an excerpt from the debug if this can help.

I can't find the reason why this is happening. I have already deleted the entire daemon set and rolled it out again, strangely enough it starts exactly the same.

### System
Openshift 4.6+ running on AWS
SignalFx SmartAgent v5.7.1
Running as Deamonset

![image](https://user-images.githubusercontent.com/22026079/119865295-d3996600-bf1b-11eb-8f25-3dd2a8b83100.png)

```
time="2021-05-27T12:53:23Z" level=info msg="Starting up agent version 5.7.1"
.....
time="2021-05-27T12:53:27Z" level=warning msg="Dropping dimension update" dimName=kubernetes_uid dimValue=72da868f-4fae-4fce-8cb0-c70b0ac55463 error="dropped dimension update, propertiesMaxBuffered exceeded"
time="2021-05-27T12:53:27Z" level=warning msg="Dropping dimension update" dimName=kubernetes_uid dimValue=565d2539-2a48-415e-bba2-824b4440deed error="dropped dimension update, propertiesMaxBuffered exceeded"
time="2021-05-27T12:53:27Z" level=warning msg="Dropping dimension update" dimName=kubernetes_uid dimValue=2a78cdff-f3d6-433a-8bf8-d52d57838aeb error="dropped dimension update, propertiesMaxBuffered exceeded"
time="2021-05-27T12:53:27Z" level=warning msg="Dropping dimension update" dimName=kubernetes_uid dimValue=61e4137b-8bf9-4c4c-ad49-a20e8297ccb3 error="dropped dimension update, propertiesMaxBuffered exceeded"
time="2021-05-27T12:53:27Z" level=warning msg="Dropping dimension update" dimName=kubernetes_uid dimValue=884f5139-882f-474a-932f-3282ed68d71a error="dropped dimension update, propertiesMaxBuffered exceeded"
....
time="2021-05-27T12:53:33Z" level=warning msg="A datapoint was overwritten in the write buffer, please consider increasing the writer.maxDatapointsBuffered config option to something greater than 25000" component=writer
time="2021-05-27T12:53:53Z" level=warning msg="A datapoint was overwritten in the write buffer, please consider increasing the writer.maxDatapointsBuffered config option to something greater than 25000" component=writer
time="2021-05-27T12:54:13Z" level=warning msg="A datapoint was overwritten in the write buffer, please consider increasing the writer.maxDatapointsBuffered config option to something greater than 25000" component=writer
time="2021-05-27T12:54:43Z" level=warning msg="A datapoint was overwritten in the write buffer, please consider increasing the writer.maxDatapointsBuffered config option to something greater than 25000" component=writer
time="2021-05-27T12:55:13Z" level=warning msg="A datapoint was overwritten in the write buffer, please consider increasing the writer.maxDatapointsBuffered config option to something greater than 25000" component=writer
time="2021-05-27T12:55:33Z" level=warning msg="A datapoint was overwritten in the write buffer, please consider increasing the writer.maxDatapointsBuffered config option to something greater than 25000" component=writer
time="2021-05-27T12:55:53Z" level=warning msg="A datapoint was overwritten in the write buffer, please consider increasing the writer.maxDatapointsBuffered config option to something greater than 25000" component=writer
time="2021-05-27T12:56:13Z" level=warning msg="A datapoint was overwritten in the write buffer, please consider increasing the writer.maxDatapointsBuffered config option to something greater than 25000" component=writer
time="2021-05-27T12:56:33Z" level=warning msg="A datapoint was overwritten in the write buffer, please consider increasing the writer.maxDatapointsBuffered config option to something greater than 25000" component=writer
time="2021-05-27T12:56:53Z" level=warning msg="A datapoint was overwritten in the write buffer, please consider increasing the writer.maxDatapointsBuffered config option to something greater than 25000" component=writer
...
# Auto restart from the Agent
..... 
# Same Errors again...

time="2021-05-27T15:02:09Z" level=error msg="Datapoints have an unknown monitorID" collectdInstance=global datapoints="[DP[nginx_connections.active\tmap[dsname:value host:ip-10-xxx-xxx-111 plugin:nginx plugin_instance:chatprotocolservice-8-gnzxs-9e43f8e-8443]\t4\t0\t2021-05-27 15:02:09.242000128 +0000 UTC] DP[connections.accepted\tmap[dsname:value host:ip-10-xxx-xxx-111 plugin:nginx plugin_instance:chatprotocolservice-8-gnzxs-9e43f8e-8443]\t211717\t3\t2021-05-27 15:02:09.242000128 +0000 UTC] DP[connections.handled\tmap[dsname:value host:ip-10-xxx-xxx-111 plugin:nginx plugin_instance:chatprotocolservice-8-gnzxs-9e43f8e-8443]\t211717\t3\t2021-05-27 15:02:09.242000128 +0000 UTC] DP[connections.failed\tmap[dsname:value host:ip-10-176-50-111 plugin:nginx plugin_instance:chatprotocolservice-8-gnzxs-9e43f8e-8443]\t0\t3\t2021-05-27 15:02:09.242000128 +0000 UTC] DP[nginx_requests\tmap[dsname:value host:ip-10-xxx-xxx-111 plugin:nginx plugin_instance:chatprotocolservice-8-gnzxs-9e43f8e-8443]\t37632\t3\t2021-05-27 15:02:09.242000128 +0000 UTC] DP[nginx_connections.reading\tmap[dsname:value host:ip-10-xxx-xxx-111 plugin:nginx plugin_instance:chatprotocolservice-8-gnzxs-9e43f8e-8443]\t0\t0\t2021-05-27 15:02:09.242000128 +0000 UTC] DP[nginx_connections.writing\tmap[dsname:value host:ip-10-xxx-xxx-111 plugin:nginx plugin_instance:chatprotocolservice-8-gnzxs-9e43f8e-8443]\t1\t0\t2021-05-27 15:02:09.242000128 +0000 UTC] DP[nginx_connections.waiting\tmap[dsname:value host:ip-10-xxx-xxx-111 plugin:nginx plugin_instance:chatprotocolservice-8-gnzxs-9e43f8e-8443]\t3\t0\t2021-05-27 15:02:09.242000128 +0000 UTC]]" monitorID=26

```

## Debug <signalfx-agent -debug>

```
WARN[0012] Dropping dimension update                     dimName=kubernetes_uid dimValue=67abfb08-c779-412e-b26c-1c6d71c30483 error="dropped dimension update, propertiesMaxBuffered exceeded"
WARN[0012] Dropping dimension update                     dimName=kubernetes_pod_uid dimValue=ea0aef92-ea41-4c9f-9a2f-7ddcdc6d4f53 error="dropped dimension update, propertiesMaxBuffered exceeded"
WARN[0012] Dropping dimension update                     dimName=kubernetes_pod_uid dimValue=a40bdcf2-ca86-46a7-a630-12fc8f59e32b error="dropped dimension update, propertiesMaxBuffered exceeded"
WARN[0012] Dropping dimension update                     dimName=kubernetes_uid dimValue=79838cb7-9dd0-4527-8d29-132af2a364a0 error="dropped dimension update, propertiesMaxBuffered exceeded"
WARN[0012] Dropping dimension update                     dimName=kubernetes_uid dimValue=be65541d-ba0f-4a59-b7fe-e82233d6f5cf error="dropped dimension update, propertiesMaxBuffered exceeded"
WARN[0012] Dropping dimension update                     dimName=kubernetes_pod_uid dimValue=b35e1541-17bd-4a14-94c3-344875ab21a1 error="dropped dimension update, propertiesMaxBuffered exceeded"
WARN[0012] Dropping dimension update                     dimName=kubernetes_pod_uid dimValue=1f972abe-3a64-4e73-9334-9a47f3142475 error="dropped dimension update, propertiesMaxBuffered exceeded"
ERRO[0015] Problem with diagnostic server                error="listen tcp 127.0.0.1:8095: bind: address already in use" host=localhost port=8095
WARN[0015] Dropping dimension update                     dimName=container_id dimValue=079a9b03e36e49a19b0e22f8682cb4c000933081f9e746a7b9d362e0959e47b0 error="dropped dimension update, propertiesMaxBuffered exceeded"
ERRO[0030] Problem with diagnostic server                error="listen tcp 127.0.0.1:8095: bind: address already in use" host=localhost port=8095
ERRO[0045] Problem with diagnostic server                error="listen tcp 127.0.0.1:8095: bind: address already in use" host=localhost port=8095
ERRO[0060] Problem with diagnostic server                error="listen tcp 127.0.0.1:8095: bind: address already in use" host=localhost port=8095
ERRO[0075] Problem with diagnostic server                error="listen tcp 127.0.0.1:8095: bind: address already in use" host=localhost port=8095
```

is there an explanation? or a way how I can better find out why this is happening or where this is coming from. I think it's a collectd / nginx monitor. But I am not sure.

Best regards Achim

**Comment by keitwb** [comment]
The most insight to this can be gained by setting the following config:

```
profiling: true
```

and then waiting until memory starts substantially increasing above normal and then running:

`curl http://<agent host>:6060/debug/pprof/heap > /tmp/heap-profile`

and post it here (it is safe to post as it only contains object allocation sizes and counts and not actual heap data) for me to look at.

There are definitely some issues sending to the ingest server but it isn't clear how or why that is related to memory growing because the buffers there are all of fixed size so things get dropped/overwritten if too many get backed up.

Also if you could post the config you are using (sanitized for tokens or any other sensitive data) that would be helpful too.

**Comment by AchimGrolimund** [comment]
hello @keitwb 
thanks for the fast answer.

here in the first step our configmap:
```
---
# Source: signalfx-agent/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: signalfx-agent
  namespace: company-signalfx
  labels:
    app: signalfx-agent
data:
  agent.yaml: |
    signalFxAccessToken: ${SFX_ACCESS_TOKEN}

    signalFxRealm: eu0
    etcPath: /hostfs/etc
    procPath: /hostfs/proc

    intervalSeconds: 10

    cluster: OCP4-PROD1

    logging:
      level: info
      format: text

    globalDimensions:
      kubernetes_cluster: OCP4-PROD1

    ingestUrl: https://someurltootelcollector.cloud/ingest/
    apiUrl: https://someurltootelcollector.cloud/api/
    traceEndpointUrl: https://someurltootelcollector.cloud/ingest/v2/trace
    eventEndpointUrl: https://someurltootelcollector.cloud/ingest/v2/event

    observers:
    - type: k8s-api

    monitors:
    - type: trace-forwarder
      # This can be changed if needed; always HTTP only.
      # Use 0.0.0.0:9080 if your app runs in a container
      # and won't talk to your Smart Agent over lo0.
      listenAddress: 0.0.0.0:9080
      # Used to add a tag to spans missing it
      defaultSpanTags:
      #Set the environment filter in SignalFx
        environment: "prod1"
      # Used to add and override a tag on a span
      #extraSpanTags:
      #SPAN_TAG_KEY: "SPAN_TAG_VALUE"

    - type: cpu
    - type: collectd/cpufreq
    - type: filesystems
      hostFSPath: /hostfs
    - type: disk-io
    - type: net-io
    - type: load
    - type: memory
    - type: collectd/protocols
    - type: collectd/signalfx-metadata
      omitProcessInfo: true
    - type: host-metadata
    - type: processlist
    - type: collectd/uptime
    - type: vmem

    # NGINX
    - type: collectd/nginx
      discoveryRule: 'Get(container_labels, "app") != "schema-registry-proxy" && target == "hostport" && container_image =~ "nginx" && private_port == 8443'
      url: "https://{{.Host}}:{{.Port}}/nginx_status"
      validateDiscoveryRule: false

    # Kubernetes
    - type: kubelet-metrics
      kubeletAPI:
        authType: serviceAccount
        url: https://localhost:10250
      datapointsToExclude:
      - dimensions:
          container_image:
           - '*pause-amd64*'
           - 'k8s.gcr.io/pause*'
        metricNames:
          - '*'
          - '!*network*'

    # Openshift cluster metrics
    - type: openshift-cluster
      kubernetesAPI:
        authType: serviceAccount
      datapointsToExclude:
      - dimensions:
        metricNames:
          - '*appliedclusterquota*'
          - '*clusterquota*'

    # Kubernetes events
    - type: kubernetes-events
      whitelistedEvents:
      - reason: FailedCreated
        involvedObjectKind: Build
      - reason: Failed
        involvedObjectKind: DeploymentConfig
      - reason: FailedCreate
        involvedObjectKind: DeploymentConfig
      - reason: FailedComputeMetricsReplicas
        involvedObjectKind: HorizontalPodAutoscaler
      - reason: FailedGetResourceMetric
        involvedObjectKind: HorizontalPodAutoscaler
      - reason: FailedCreate
        involvedObjectKind: Job
      - reason: BackOff
        involvedObjectKind: Pod
      - reason: Failed
        involvedObjectKind: Pod
      - reason: FailedCreatePodSandbox
        involvedObjectKind: Pod
      - reason: FailedMount
        involvedObjectKind: Pod
      - reason: FailedPodSandBoxStatus
        involvedObjectKind: Pod
      - reason: FailedScheduling
        involvedObjectKind: Pod
      - reason: SandboxChanged
        involvedObjectKind: Pod
      - reason: Unhealthy
        involvedObjectKind: Pod
      - reason: FailedCreate
        involvedObjectKind: ReplicationController

    - type: prometheus-exporter
      discoveryRule: port == 4444 && kubernetes_namespace =~ "checkbot"
      extraDimensions:
        metric_source: checkbot
      useServiceAccount: true
      useHTTPS: true
      skipVerify: true

    collectd:
      readThreads: 5
      writeQueueLimitHigh: 500000
      writeQueueLimitLow: 400000
      timeout: 40
      logLevel: info
    enableBuiltInFiltering: true
    metricsToExclude:
      # The StackDriver metadata-agent pod on GKE restarts every few minutes so
      # ignore its containers
      - dimensions:
          container_spec_name: metadata-agent

    writer:
      traceExportFormat: sapm
```
