### ISSUE TITLE
kubernetes-events monitor not working with 3.0.2

### ISSUE THREAD

**Issue by brycekahle** [signalfx/signalfx-agent#226]
I'm receiving this error when using the docker image: `quay.io/signalfx/signalfx-agent:3.0.2`
```
Unknown monitor type kubernetes-events
```

My configmap sections looks like this:
```
    monitors:
      - type: kubernetes-events
        whitelistedEvents:
        - reason: ScaleDownEmpty
          involvedObjectKind: ConfigMap
        - reason: ScaledUpGroup
          involvedObjectKind: ConfigMap
```
