### ISSUE TITLE
Ansible Role

### ISSUE THREAD

**Issue by camdixon** [signalfx/signalfx-agent#261]
The Ansible Role is not in Ansible Galaxy or mentioned on the main README.md page.  

1) deployments/ansible/meta/main.yml you should change the author line to:
```
---
galaxy_info:
  author: signalfx
  description: Ansible role to install and configure the SignalFx Smart Agent
  company: SignalFx, Inc.
  license: Apache-2.0
  min_ansible_version: 1.9
```

This will allow you to submit your Smart Agent for SignalFx to Ansible Galaxy for easier adoption by Ansible users.  Also, your docs do not say how to install the role, but it would be helpful to other users.  I had to actually manually put the files there - or someone would need to install the Ansible specific folder by using the Github method described when [Installing SignalFx for Ansible](http://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#installing-roles)

After you're in Ansible Galaxy it would be the preferred method in the README.md of Ansible to show a simple role installation, and then playbook use.  I realize you already have a sample playbook - the idea I'm suggesting is to make this a simpler install for onboarding new clients you prospect.

`ansible-galaxy --install signalfx.signalfx-agent`

The above command assumes Ansible Galaxy submission, and meta/main.yaml edit of "author" line to suggestion above.

**Comment by camdixon** [comment]
Also,

In your meta file you mention `min_ansible_version: 1.9` however you use `import_task` functionality in the role based on OS Family.  This will need to be updated to `min_ansible_version 2.4`.

**Comment by camdixon** [comment]
>TASK [signalfx-agent-install : Add an Apt signing key for Signalfx Agent] ***************************
fatal: [sc-cbs-hub01]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key --keyring /etc/apt/trusted.gpg.d/signalfx.gpg add -", "msg": "ERROR: This command can only be used by root.", "rc": 1, "stderr": "ERROR: This command can only be used by root.\n", "stderr_lines": ["ERROR: This command can only be used by root."], "stdout": "", "stdout_lines": []}

In the roles -> signalfx-agent/tasks/debian_repo.yml
```
---
- name: Add an Apt signing key for Signalfx Agent
  apt_key:
    url: "{{ repo_base_url }}/debian.gpg"
    keyring: /etc/apt/trusted.gpg.d/signalfx.gpg
    state: present
  become: yes
```
Adding `become: yes` fixes this, and allows use of a vault password or `ansible-playbook -K playbook-name.yml`

Also applied to other 2 tasks in this file, because permission denied error received with these tasks.
