### ISSUE TITLE
Chef cookbook agent config yaml doesn't work with smart agent

### ISSUE THREAD

**Issue by pvanliew** [signalfx/signalfx-agent#549]
Currently, the chef cookbook will create an agent.yaml from conf attributes with json-ified yaml, that the java smart agent, in this case, can't use, and so does not start up.

Such as:
```
monitors: [{type: "trace-forwarder", listenAddress: "127.0.0.1:9080"}, {"type": "collectd/cpu"}]
signalFxAccessToken: "howdy"
traceEndpointUrl: "http://somewhere:8080/v1/trace"
writer: {"sendTraceHostCorrelationMetrics": true}
```

When correct yaml that the agent needs to start is:
```
monitors:
  - type: trace-forwarder
    listenAddress: 127.0.0.1:9080
  - type: collectd/cpu
signalFxAccessToken: howdy
traceEndpointUrl: http://somewhere:8080/v1/trace
writer:
  sendTraceHostCorrelationMetrics: true
```
