### ISSUE TITLE
Redis ListLength does not seem to honor DBIndex

### ISSUE THREAD

**Issue by joshma** [signalfx/signalfx-agent#604]
Hi there, I'm still trying to troubleshoot more and see if I can get a more precise issue, but we're observing that the Redis integration is only reporting DBIndex=0 and is ignoring our configuration of DBIndex=2.

Our agent.yaml file:

```
signalFxAccessToken: {"#from": "env:ACCESS_TOKEN"}
ingestUrl: {"#from": "env:INGEST_URL", optional: true}
apiUrl: {"#from": "env:API_URL", optional: true}

intervalSeconds: {"#from": "env:INTERVAL_SECONDS", default: 10}

logging:
  level: {"#from": "env:LOG_LEVEL", default: "info"}

monitors:
  - type: collectd/redis
    host: {"#from": "env:REDIS_HOST"}
    port: {"#from": "env:REDIS_PORT", default: 6379}
    sendListLengths:
      - databaseIndex: 2
        keyPattern: '*'
    disableHostDimensions: true
    extraDimensions:
      deploy: {"#from": "env:DEPLOY"}
```

Within SignalFx, we're seeing keys being reported for db `0`. Any chance the db number config is being ignored?

**Comment by keitwb** [comment]
That `sendListLengths` config option is only used to configure the sending of list length metrics.  You are saying to send the `gauge.key_llen` metric for every list value in database 2, but it doesn't prevent the general stats for the keyspace 0 from being sent.  Are you seeing `gauge.key_llen` metrics for db 0 as well?  If so, that is definitely a bug.  You should only see those for db 2.

Most of the metrics sent are derived from the [INFO command](https://redis.io/commands/INFO).  If you want to exclude keyspace metrics about db0 (e.g. `gauge.db0_keys`, `gauge.db0_expires`, and `gauge.db0_avg_ttl`) you can just use this filter in your monitor config:

```
monitors:
  - type: collectd/redis
    host: {"#from": "env:REDIS_HOST"}
    port: {"#from": "env:REDIS_PORT", default: 6379}
    sendListLengths:
      - databaseIndex: 2
        keyPattern: '*'
    disableHostDimensions: true
    extraDimensions:
      deploy: {"#from": "env:DEPLOY"}
    metricsToExclude:
      - metricName: *db0_*
```

**Comment by joshma** [comment]
> Are you seeing `gauge.key_llen` metrics for db 0 as well? If so, that is definitely a bug. You should only see those for db 2.
Yes, that's what I meant - we're primarily interested in `gauge.key_llen`, because we're using it to measure celery queue lengths.

We're seeing the list lengths from db 0 and not 2 (and a bunch of errors since `*` matches a lot of non-lists).

**Comment by keitwb** [comment]
I am not able to reproduce this.  I used this config:

```
monitors:
  - type: collectd/redis
    discoveryRule: 'container_image =~ "redis"'
    sendListLengths:
     - keyPattern: '*'
       databaseIndex: 2
```

And created two lists, one in database 0 and one in database 2, and only got `gauge.key_llen` metrics for the one in db 2.  If I change `databaseIndex` to 0 then I stop getting then metric for db 2 and only for db 0.

What version of the agent are you using?  I am testing against the latest but this could have possibly been a bug that was fixed a while back.
